name: firstworkflow
on: 
  workflow_dispatch: 
jobs:
  terraform_install:
    runs-on: ubuntu-latest
    steps:
      - name: code-checput
        uses: actions/checkout@v6.0.3

      - name: Terraform install
        uses: hashicorp/setup-terraform@v2.0.3
        

      - name: Terraform-init
        run: terraform init

      - name: Terraform-Plan
        run: terraform plan
        
        
        
    
